version: '3'

services:

  api:
    build: ./api
    container_name: api-random-team-picker
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - ./api:/api
    depends_on:
      - db
    ports:
      - 3000:3000
    networks:
      - random-team-picker-network

  db:
    image: mysql:8.0
    restart: always
    container_name: db-random-team-picker
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: random-team-picker-db
    networks:
      - random-team-picker-network

  frontend:
    build: ./frontend
    container_name: frontend-random-team-picker
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - ./frontend:/frontend
    ports:
      - 3001:3001
    networks:
      - random-team-picker-network

networks:
  random-team-picker-network:
    driver: bridge
